### ISSUE TITLE
Issue 24:	MarkerWithLabel : problem of overlapping labels when two markers are in the same position

### ISSUE THREAD

**Issue by tzfrs** [printercu/google-maps-utility-library-v3-read-only#3]
On your google repo

https://code.google.com/p/google-maps-utility-library-v3/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Priority%20Fixed%20Owner%20Summary%20Stars&groupby=&sort=&id=24

someone suggested a fix for the problem of overlapping labels

> I found only one solution: (version 1.10)
instead of 
line 141:
this.getPanes().overlayImage.appendChild(this.labelDiv_);
use this:
this.getPanes().markerLayer.appendChild(this.labelDiv_);

> The overlayImage pane is pane which every elements overlay the any element of image and marker layer.

> Because z-index work only in theier stack context, so any change of z-index can't solve this problem. Onle when you add the label and marker image to same pane, you can work with z-index.

> Currently it's work for me.

Is there a reason this isn't implemented yet?

**Comment by printercu** [comment]
Oh, it's not my repo :) I've just cloned it as git repo to be able to use as submodule. And this repo is read-only 'cause it's synced with svn periodically.
