### ISSUE TITLE
MarkerWithLabel  - ZIndex issue because of the different panes for label and pin

### ISSUE THREAD

**Issue by adrianaxente** [printercu/google-maps-utility-library-v3-read-only#4]
The Z-Index for the MarkerWithLabel does not work properly because the marker is pushed to "markerLayer" pane and the lablel is pushed to "overlayImage" pane.Because of this difference the label and marker will Stick together.

- One possible solution would be to push the label to the same pane as the marker: "markerLayer"

**Comment by printercu** [comment]
Hi! Can you submit PR with this commit please?

**Comment by printercu** [comment]
closed with #5

**Comment by eric-chantigny** [comment]
This doesn't seem to be working for me at all.  My labels are stacked on top of the pins when there's multiple pins on the same spot.

**Comment by printercu** [comment]
I don't use it, so i'm not able to help. Can you try commit c624d8c, does it work?

**Comment by eric-chantigny** [comment]
The commit you are suggesting is for the Marker Clusterer, this is for the Marker with Labels.  
But thanks, I figured out a work around with css to make it work.  Doesn't look like there's a real fix on the google maps side to get this done.

**Comment by printercu** [comment]
This commit is right before merged PR #5, so it could work if the issue related to the PR.
