### ISSUE TITLE
Is optimized = false really necessary when calling google.maps.Marker?

### ISSUE THREAD

**Issue by LowSociety** [printercu/google-maps-utility-library-v3-read-only#6]
I totally understand that optimized rendering isn't implemented in the `MarkerWithLabel` class but is it necessary to force this option to be `false` when calling `google.maps.Marker`? It significantly slows down the native rendering (from 0-1ms to 20-60ms per marker) and to my knowledge shouldn't break the default behavior of `MarkerWithLabel` when set to `true`.

In my project I use transparent 1x1px gifs as icons for the `Marker` and utilize only the `MarkerWithLabel.label` as a visible marker on the map. Whether or not the transparent pixels are "optimized" when rendered should not affect me.

**Comment by printercu** [comment]
Sorry, don't understand what you're asking about. Haven't worked neither with `MarkerWithLabel` nor `optimized`. Can you provide some more info or links to the code in repo?

Please notice, that this repo is just git mirror of original svn repo. I haven't written a line of code into it. So maybe you can get answer faster on stackoverflow.

**Comment by LowSociety** [comment]
Sorry! This ended up in the wrong repo.
