### ISSUE TITLE
geolocationmarker-compiled.js - 404 not found

### ISSUE THREAD

**Issue by morkov4o** [printercu/google-maps-utility-library-v3-read-only#8]

**Comment by printercu** [comment]
Wonderful issue! Everything is clear and understandable.

**Comment by morkov4o** [comment]
https://github.com/printercu/google-maps-utility-library-v3-read-only/blob/master/geolocationmarker/examples/mylocation.html 

Line 15: you are including //google-maps-utility-library-v3.googlecode.com/svn/trunk/geolocationmarker/src/geolocationmarker-compiled.js and the link returns Error 404 not found.

**Comment by printercu** [comment]
In the README: `... However exaples and some compiled files are not updated.`

Feel free to prepare PR for this.
