### ISSUE TITLE
Markers with label not showing in google chrome after deploying on IIS production

### ISSUE THREAD

**Issue by akash2go** [printercu/google-maps-utility-library-v3-read-only#9]
My application is using markerwithlabel library.It works well while in development environment on google chrome.But after deploying the application on IIS production , the markers are not visible in google chrome while they are visible in IE and Firefox.Please suggest a solution as most of the users are having google chrome installed on their machine.

**Comment by printercu** [comment]
I haven't written this library, so I can't give any solutions. Check developer console for any errors.
Try to ask on stackoverflow, may be someone have faced same issue.
